/**
 * Generates G-code from a list of tool operations.
 * @param {Array<Array<{x: number, y: number, z: number}>>} toolpaths - Array of tool operations, each is an array of points.
 * @param {Object} [options] - Optional G-code settings.
 * @returns {string} G-code as a string.
 */
function generate_gcode(toolpaths, options = {}) {
  // toolpaths: array of arrays of points
  // Assumes all coordinates are in mm, Z is up, safe height is 5mm above start Z
  // For flatten operations, we assume Z=0 is the top of the stock (CNC zeroed at top surface)
  // This is the most typical workflow for flattening. Eventually, this may be configurable.
  const lines = [];
  lines.push('; Generated by nerd-cnc');
  if (options.origin_z !== undefined) {
    lines.push('; Assumption: Z=0 is the top of the stock for flatten operations');
  }
  lines.push('G21 ; Set units to mm');
  lines.push('G90 ; Absolute positioning');

  // Feedrate and spindle speed (default or from options)
  const feedrate = options.feedrate || 1000;
  const spindle_speed = options.spindle_speed || undefined;
  lines.push(`G1 F${feedrate} ; Set feedrate`);
  if (spindle_speed) {
    lines.push(`M3 S${spindle_speed} ; Spindle on`);
  }

  for (const op of toolpaths) {
    if (!op || op.length === 0) continue;
    const start = op[0];
    const safe_z = options.safe_z ? options.safe_z : start.z + 5;
    // Retract to safe height before rapid move
    lines.push(`G0 Z${(options.origin_z !== undefined ? (options.safe_z - options.origin_z) : safe_z).toFixed(3)}`);
    // Rapid move to start XY at safe height
    lines.push(`G0 X${start.x.toFixed(3)} Y${start.y.toFixed(3)}`);
    // Plunge to start Z
    const start_z = options.origin_z !== undefined ? (start.z - options.origin_z) : start.z;
    lines.push(`G1 Z${start_z.toFixed(3)}`);
    // Cut path for this operation
    for (const pt of op) {
      const z = options.origin_z !== undefined ? (pt.z - options.origin_z) : pt.z;
      lines.push(`G1 X${pt.x.toFixed(3)} Y${pt.y.toFixed(3)} Z${z.toFixed(3)}`);
    }
    // Retract to safe height at end of operation
    lines.push(`G0 Z${(options.origin_z !== undefined ? (options.safe_z - options.origin_z) : safe_z).toFixed(3)}`);
  }

  if (spindle_speed) {
    lines.push('M5 ; Spindle off');
  }
  lines.push('M2 ; End of program');
  return lines.join('\n');
}

module.exports = { generate_gcode };
