/**
 * Generates G-code from a toolpath.
 * @param {Array<{x: number, y: number, z: number}>} toolpath - Array of points.
 * @param {Object} [options] - Optional G-code settings.
 * @returns {string} G-code as a string.
 */
function generate_gcode(toolpath, options = {}) {
  const lines = [];
  lines.push('; Generated by nerd-cnc');
  lines.push('G21 ; Set units to mm');
  lines.push('G90 ; Absolute positioning');
  lines.push('G1 F1000 ; Set default feedrate');

  if (toolpath.length === 0) return lines.join('\n');

  // Move to start point above part
  const start = toolpath[0];
  lines.push(`G0 X${start.x.toFixed(3)} Y${start.y.toFixed(3)} Z${(start.z + 5).toFixed(3)}`);

  // Plunge to first Z
  lines.push(`G1 Z${start.z.toFixed(3)}`);

  // Cut path
  for (const pt of toolpath) {
    lines.push(`G1 X${pt.x.toFixed(3)} Y${pt.y.toFixed(3)} Z${pt.z.toFixed(3)}`);
  }

  // Retract at end
  lines.push(`G0 Z${(start.z + 5).toFixed(3)}`);
  lines.push('M2 ; End of program');
  return lines.join('\n');
}

module.exports = { generate_gcode };
